/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as IndustryIndexRouteImport } from './routes/industry.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsSolutionRouteImport } from './routes/solutions.$solution'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'
import { Route as LocationsCityRouteImport } from './routes/locations.$city'
import { Route as IndustryIndustryRouteImport } from './routes/industry.$industry'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiBlogWebhookRouteImport } from './routes/api.blog.webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryIndexRoute = IndustryIndexRouteImport.update({
  id: '/industry/',
  path: '/industry/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSolutionRoute = SolutionsSolutionRouteImport.update({
  id: '/solutions/$solution',
  path: '/solutions/$solution',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsCityRoute = LocationsCityRouteImport.update({
  id: '/locations/$city',
  path: '/locations/$city',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryIndustryRoute = IndustryIndustryRouteImport.update({
  id: '/industry/$industry',
  path: '/industry/$industry',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogWebhookRoute = ApiBlogWebhookRouteImport.update({
  id: '/api/blog/webhook',
  path: '/api/blog/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industry/$industry': typeof IndustryIndustryRoute
  '/locations/$city': typeof LocationsCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/solutions/$solution': typeof SolutionsSolutionRoute
  '/blog/': typeof BlogIndexRoute
  '/industry/': typeof IndustryIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/api/blog/webhook': typeof ApiBlogWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industry/$industry': typeof IndustryIndustryRoute
  '/locations/$city': typeof LocationsCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/solutions/$solution': typeof SolutionsSolutionRoute
  '/blog': typeof BlogIndexRoute
  '/industry': typeof IndustryIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/api/blog/webhook': typeof ApiBlogWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industry/$industry': typeof IndustryIndustryRoute
  '/locations/$city': typeof LocationsCityRoute
  '/services/$service': typeof ServicesServiceRoute
  '/solutions/$solution': typeof SolutionsSolutionRoute
  '/blog/': typeof BlogIndexRoute
  '/industry/': typeof IndustryIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/api/blog/webhook': typeof ApiBlogWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/industry/$industry'
    | '/locations/$city'
    | '/services/$service'
    | '/solutions/$solution'
    | '/blog/'
    | '/industry/'
    | '/locations/'
    | '/services/'
    | '/solutions/'
    | '/api/blog/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/industry/$industry'
    | '/locations/$city'
    | '/services/$service'
    | '/solutions/$solution'
    | '/blog'
    | '/industry'
    | '/locations'
    | '/services'
    | '/solutions'
    | '/api/blog/webhook'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/industry/$industry'
    | '/locations/$city'
    | '/services/$service'
    | '/solutions/$solution'
    | '/blog/'
    | '/industry/'
    | '/locations/'
    | '/services/'
    | '/solutions/'
    | '/api/blog/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustryIndustryRoute: typeof IndustryIndustryRoute
  LocationsCityRoute: typeof LocationsCityRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  SolutionsSolutionRoute: typeof SolutionsSolutionRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IndustryIndexRoute: typeof IndustryIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
  ApiBlogWebhookRoute: typeof ApiBlogWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/': {
      id: '/industry/'
      path: '/industry'
      fullPath: '/industry/'
      preLoaderRoute: typeof IndustryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$solution': {
      id: '/solutions/$solution'
      path: '/solutions/$solution'
      fullPath: '/solutions/$solution'
      preLoaderRoute: typeof SolutionsSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$city': {
      id: '/locations/$city'
      path: '/locations/$city'
      fullPath: '/locations/$city'
      preLoaderRoute: typeof LocationsCityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industry/$industry': {
      id: '/industry/$industry'
      path: '/industry/$industry'
      fullPath: '/industry/$industry'
      preLoaderRoute: typeof IndustryIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/webhook': {
      id: '/api/blog/webhook'
      path: '/api/blog/webhook'
      fullPath: '/api/blog/webhook'
      preLoaderRoute: typeof ApiBlogWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustryIndustryRoute: IndustryIndustryRoute,
  LocationsCityRoute: LocationsCityRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  SolutionsSolutionRoute: SolutionsSolutionRoute,
  BlogIndexRoute: BlogIndexRoute,
  IndustryIndexRoute: IndustryIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
  ApiBlogWebhookRoute: ApiBlogWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
